/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ConnectionEvent } from './connectionEvent';
import { ConnectionType } from './connectionType';
import { Population } from './population';
import { Session } from './session';
import { User } from './user';

export class Connection {
    'active'?: boolean;
    'connectionID'?: string;
    'events'?: Array<ConnectionEvent>;
    'connectionTypeId'?: number;
    'connectionType'?: ConnectionType;
    'populationId'?: number;
    'population'?: Population;
    'sessionId'?: number;
    'session'?: Session;
    'userId'?: string;
    'user'?: User;
    'id'?: number;
    'deleted'?: boolean;
    'createdDate'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean"
        },
        {
            "name": "connectionID",
            "baseName": "connectionID",
            "type": "string"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<ConnectionEvent>"
        },
        {
            "name": "connectionTypeId",
            "baseName": "connectionTypeId",
            "type": "number"
        },
        {
            "name": "connectionType",
            "baseName": "connectionType",
            "type": "ConnectionType"
        },
        {
            "name": "populationId",
            "baseName": "populationId",
            "type": "number"
        },
        {
            "name": "population",
            "baseName": "population",
            "type": "Population"
        },
        {
            "name": "sessionId",
            "baseName": "sessionId",
            "type": "number"
        },
        {
            "name": "session",
            "baseName": "session",
            "type": "Session"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "User"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Connection.attributeTypeMap;
    }
}

