/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DeviceConfigurationProperty } from './deviceConfigurationProperty';
import { DeviceProperty } from './deviceProperty';
import { Population } from './population';
import { User } from './user';

export class Device {
    'guid'?: string;
    'name'?: string;
    'configuration'?: Array<DeviceConfigurationProperty>;
    'properties'?: Array<DeviceProperty>;
    'ownerId'?: string;
    'owner'?: User;
    'populationId'?: number;
    'population'?: Population;
    'id'?: number;
    'deleted'?: boolean;
    'createdDate'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "guid",
            "baseName": "guid",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "Array<DeviceConfigurationProperty>"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Array<DeviceProperty>"
        },
        {
            "name": "ownerId",
            "baseName": "ownerId",
            "type": "string"
        },
        {
            "name": "owner",
            "baseName": "owner",
            "type": "User"
        },
        {
            "name": "populationId",
            "baseName": "populationId",
            "type": "number"
        },
        {
            "name": "population",
            "baseName": "population",
            "type": "Population"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Device.attributeTypeMap;
    }
}

