/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class IdentityUserClaimString {
    'id'?: number;
    'userId'?: string;
    'claimType'?: string;
    'claimValue'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "string"
        },
        {
            "name": "claimType",
            "baseName": "claimType",
            "type": "string"
        },
        {
            "name": "claimValue",
            "baseName": "claimValue",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return IdentityUserClaimString.attributeTypeMap;
    }
}

