/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MeasureType } from './measureType';
import { Session } from './session';

export class Measure {
    'start'?: Date;
    'end'?: Date;
    'ordinal'?: number;
    'json'?: string;
    'complete'?: boolean;
    'lock'?: boolean;
    'measureTypeId'?: number;
    'measureType'?: MeasureType;
    'sessionId'?: number;
    'session'?: Session;
    'id'?: number;
    'deleted'?: boolean;
    'createdDate'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "start",
            "baseName": "start",
            "type": "Date"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "Date"
        },
        {
            "name": "ordinal",
            "baseName": "ordinal",
            "type": "number"
        },
        {
            "name": "json",
            "baseName": "json",
            "type": "string"
        },
        {
            "name": "complete",
            "baseName": "complete",
            "type": "boolean"
        },
        {
            "name": "lock",
            "baseName": "lock",
            "type": "boolean"
        },
        {
            "name": "measureTypeId",
            "baseName": "measureTypeId",
            "type": "number"
        },
        {
            "name": "measureType",
            "baseName": "measureType",
            "type": "MeasureType"
        },
        {
            "name": "sessionId",
            "baseName": "sessionId",
            "type": "number"
        },
        {
            "name": "session",
            "baseName": "session",
            "type": "Session"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Measure.attributeTypeMap;
    }
}

