/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NotificationLog } from './notificationLog';
import { NotificationRecipient } from './notificationRecipient';
import { NotificationScheduleType } from './notificationScheduleType';
import { NotificationType } from './notificationType';
import { Population } from './population';

export class Notification {
    'title'?: string;
    'body'?: string;
    'scheduledTime'?: Date;
    'notificationTypeId'?: number;
    'notificationType'?: NotificationType;
    'notificationScheduleTypeId'?: number;
    'notificationScheduleType'?: NotificationScheduleType;
    'populationId'?: number;
    'population'?: Population;
    'logs'?: Array<NotificationLog>;
    'recipients'?: Array<NotificationRecipient>;
    'id'?: number;
    'deleted'?: boolean;
    'createdDate'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string"
        },
        {
            "name": "body",
            "baseName": "body",
            "type": "string"
        },
        {
            "name": "scheduledTime",
            "baseName": "scheduledTime",
            "type": "Date"
        },
        {
            "name": "notificationTypeId",
            "baseName": "notificationTypeId",
            "type": "number"
        },
        {
            "name": "notificationType",
            "baseName": "notificationType",
            "type": "NotificationType"
        },
        {
            "name": "notificationScheduleTypeId",
            "baseName": "notificationScheduleTypeId",
            "type": "number"
        },
        {
            "name": "notificationScheduleType",
            "baseName": "notificationScheduleType",
            "type": "NotificationScheduleType"
        },
        {
            "name": "populationId",
            "baseName": "populationId",
            "type": "number"
        },
        {
            "name": "population",
            "baseName": "population",
            "type": "Population"
        },
        {
            "name": "logs",
            "baseName": "logs",
            "type": "Array<NotificationLog>"
        },
        {
            "name": "recipients",
            "baseName": "recipients",
            "type": "Array<NotificationRecipient>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Notification.attributeTypeMap;
    }
}

