/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Measure } from './measure';
import { Population } from './population';
import { SessionProperty } from './sessionProperty';
import { SessionStatus } from './sessionStatus';
import { SessionType } from './sessionType';
import { Stimulation } from './stimulation';
import { User } from './user';

export class Session {
    'start'?: Date;
    'end'?: Date;
    'complete'?: boolean;
    'administratorId'?: string;
    'administrator'?: User;
    'populationId'?: number;
    'population'?: Population;
    'sessionStatusId'?: number;
    'sessionStatus'?: SessionStatus;
    'sessionTypeId'?: number;
    'sessionType'?: SessionType;
    'subjectId'?: string;
    'subject'?: User;
    'stimulationId'?: number;
    'stimulation'?: Stimulation;
    'measures'?: Array<Measure>;
    'properties'?: Array<SessionProperty>;
    'id'?: number;
    'deleted'?: boolean;
    'createdDate'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "start",
            "baseName": "start",
            "type": "Date"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "Date"
        },
        {
            "name": "complete",
            "baseName": "complete",
            "type": "boolean"
        },
        {
            "name": "administratorId",
            "baseName": "administratorId",
            "type": "string"
        },
        {
            "name": "administrator",
            "baseName": "administrator",
            "type": "User"
        },
        {
            "name": "populationId",
            "baseName": "populationId",
            "type": "number"
        },
        {
            "name": "population",
            "baseName": "population",
            "type": "Population"
        },
        {
            "name": "sessionStatusId",
            "baseName": "sessionStatusId",
            "type": "number"
        },
        {
            "name": "sessionStatus",
            "baseName": "sessionStatus",
            "type": "SessionStatus"
        },
        {
            "name": "sessionTypeId",
            "baseName": "sessionTypeId",
            "type": "number"
        },
        {
            "name": "sessionType",
            "baseName": "sessionType",
            "type": "SessionType"
        },
        {
            "name": "subjectId",
            "baseName": "subjectId",
            "type": "string"
        },
        {
            "name": "subject",
            "baseName": "subject",
            "type": "User"
        },
        {
            "name": "stimulationId",
            "baseName": "stimulationId",
            "type": "number"
        },
        {
            "name": "stimulation",
            "baseName": "stimulation",
            "type": "Stimulation"
        },
        {
            "name": "measures",
            "baseName": "measures",
            "type": "Array<Measure>"
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Array<SessionProperty>"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return Session.attributeTypeMap;
    }
}

