/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Population } from './population';
import { SessionTypeMeasureType } from './sessionTypeMeasureType';
import { StimulationType } from './stimulationType';

export class SessionType {
    'name'?: string;
    'description'?: string;
    'ordinal'?: number;
    'populationId'?: number;
    'population'?: Population;
    'stimulationTypeId'?: number;
    'stimulationType'?: StimulationType;
    'sessionTypeMeasureTypes'?: Array<SessionTypeMeasureType>;
    'lock'?: boolean;
    'id'?: number;
    'deleted'?: boolean;
    'createdDate'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "ordinal",
            "baseName": "ordinal",
            "type": "number"
        },
        {
            "name": "populationId",
            "baseName": "populationId",
            "type": "number"
        },
        {
            "name": "population",
            "baseName": "population",
            "type": "Population"
        },
        {
            "name": "stimulationTypeId",
            "baseName": "stimulationTypeId",
            "type": "number"
        },
        {
            "name": "stimulationType",
            "baseName": "stimulationType",
            "type": "StimulationType"
        },
        {
            "name": "sessionTypeMeasureTypes",
            "baseName": "sessionTypeMeasureTypes",
            "type": "Array<SessionTypeMeasureType>"
        },
        {
            "name": "lock",
            "baseName": "lock",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return SessionType.attributeTypeMap;
    }
}

