/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { MeasureType } from './measureType';
import { SessionType } from './sessionType';

export class SessionTypeMeasureType {
    'trigger'?: boolean;
    'ordinal'?: number;
    'measureTypeId'?: number;
    'measureType'?: MeasureType;
    'sessionTypeId'?: number;
    'sessionType'?: SessionType;
    'lock'?: boolean;
    'id'?: number;
    'deleted'?: boolean;
    'createdDate'?: Date;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "trigger",
            "baseName": "trigger",
            "type": "boolean"
        },
        {
            "name": "ordinal",
            "baseName": "ordinal",
            "type": "number"
        },
        {
            "name": "measureTypeId",
            "baseName": "measureTypeId",
            "type": "number"
        },
        {
            "name": "measureType",
            "baseName": "measureType",
            "type": "MeasureType"
        },
        {
            "name": "sessionTypeId",
            "baseName": "sessionTypeId",
            "type": "number"
        },
        {
            "name": "sessionType",
            "baseName": "sessionType",
            "type": "SessionType"
        },
        {
            "name": "lock",
            "baseName": "lock",
            "type": "boolean"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "deleted",
            "baseName": "deleted",
            "type": "boolean"
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date"
        }    ];

    static getAttributeTypeMap() {
        return SessionTypeMeasureType.attributeTypeMap;
    }
}

