/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SessionDTO {
    'start'?: Date;
    'administratorId'?: string;
    'sessionStatusId'?: number;
    'sessionTypeId'?: number;
    'subjectId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "start",
            "baseName": "start",
            "type": "Date"
        },
        {
            "name": "administratorId",
            "baseName": "administratorId",
            "type": "string"
        },
        {
            "name": "sessionStatusId",
            "baseName": "sessionStatusId",
            "type": "number"
        },
        {
            "name": "sessionTypeId",
            "baseName": "sessionTypeId",
            "type": "number"
        },
        {
            "name": "subjectId",
            "baseName": "subjectId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SessionDTO.attributeTypeMap;
    }
}

