/* tslint:disable */
/* eslint-disable */
/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    NotificationType,
    NotificationTypeFromJSON,
    NotificationTypeToJSON,
} from '../models';

/**
 * 
 */
export class NotificationTypesApi extends runtime.BaseAPI {

    /**
     */
    async getRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<NotificationType>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v2.0/notificationtypes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(NotificationTypeFromJSON));
    }

    /**
     */
    async get(initOverrides?: RequestInit): Promise<Array<NotificationType>> {
        const response = await this.getRaw(initOverrides);
        return await response.value();
    }

}
