/* tslint:disable */
/* eslint-disable */
/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Session,
    SessionFromJSON,
    SessionToJSON,
    SessionDTO,
    SessionDTOFromJSON,
    SessionDTOToJSON,
} from '../models';

export interface DeleteRequest {
    id: number;
    populationId: string;
}

export interface GetRequest {
    populationId: number;
}

export interface GetSessionRequest {
    id: number;
    populationId: string;
}

export interface PostRequest {
    populationId: number;
    sessionDTO?: SessionDTO;
}

export interface PutRequest {
    id: number;
    populationId: string;
    session?: Session;
}

/**
 * 
 */
export class SessionsApi extends runtime.BaseAPI {

    /**
     */
    async _deleteRaw(requestParameters: DeleteRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling _delete.');
        }

        if (requestParameters.populationId === null || requestParameters.populationId === undefined) {
            throw new runtime.RequiredError('populationId','Required parameter requestParameters.populationId was null or undefined when calling _delete.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v2.0/populations/{populationId}/sessions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"populationId"}}`, encodeURIComponent(String(requestParameters.populationId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async _delete(requestParameters: DeleteRequest, initOverrides?: RequestInit): Promise<void> {
        await this._deleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async getRaw(requestParameters: GetRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Session>>> {
        if (requestParameters.populationId === null || requestParameters.populationId === undefined) {
            throw new runtime.RequiredError('populationId','Required parameter requestParameters.populationId was null or undefined when calling get.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v2.0/populations/{populationId}/sessions`.replace(`{${"populationId"}}`, encodeURIComponent(String(requestParameters.populationId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SessionFromJSON));
    }

    /**
     */
    async get(requestParameters: GetRequest, initOverrides?: RequestInit): Promise<Array<Session>> {
        const response = await this.getRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSessionRaw(requestParameters: GetSessionRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Session>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getSession.');
        }

        if (requestParameters.populationId === null || requestParameters.populationId === undefined) {
            throw new runtime.RequiredError('populationId','Required parameter requestParameters.populationId was null or undefined when calling getSession.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/v2.0/populations/{populationId}/sessions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"populationId"}}`, encodeURIComponent(String(requestParameters.populationId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionFromJSON(jsonValue));
    }

    /**
     */
    async getSession(requestParameters: GetSessionRequest, initOverrides?: RequestInit): Promise<Session> {
        const response = await this.getSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postRaw(requestParameters: PostRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Session>> {
        if (requestParameters.populationId === null || requestParameters.populationId === undefined) {
            throw new runtime.RequiredError('populationId','Required parameter requestParameters.populationId was null or undefined when calling post.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        const response = await this.request({
            path: `/v2.0/populations/{populationId}/sessions`.replace(`{${"populationId"}}`, encodeURIComponent(String(requestParameters.populationId))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SessionDTOToJSON(requestParameters.sessionDTO),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionFromJSON(jsonValue));
    }

    /**
     */
    async post(requestParameters: PostRequest, initOverrides?: RequestInit): Promise<Session> {
        const response = await this.postRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async putRaw(requestParameters: PutRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling put.');
        }

        if (requestParameters.populationId === null || requestParameters.populationId === undefined) {
            throw new runtime.RequiredError('populationId','Required parameter requestParameters.populationId was null or undefined when calling put.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        const response = await this.request({
            path: `/v2.0/populations/{populationId}/sessions/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))).replace(`{${"populationId"}}`, encodeURIComponent(String(requestParameters.populationId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SessionToJSON(requestParameters.session),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async put(requestParameters: PutRequest, initOverrides?: RequestInit): Promise<void> {
        await this.putRaw(requestParameters, initOverrides);
    }

}
