/*
 * TaskFlow API
 *
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing DevicePropertiesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DevicePropertiesApiTests : IDisposable
    {
        private DevicePropertiesApi instance;

        public DevicePropertiesApiTests()
        {
            instance = new DevicePropertiesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DevicePropertiesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DevicePropertiesApi
            //Assert.IsType<DevicePropertiesApi>(instance);
        }

        /// <summary>
        /// Test Delete
        /// </summary>
        [Fact]
        public void DeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //string populationId = null;
            //string deviceId = null;
            //instance.Delete(id, populationId, deviceId);
        }

        /// <summary>
        /// Test Get
        /// </summary>
        [Fact]
        public void GetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int deviceId = null;
            //string populationId = null;
            //var response = instance.Get(deviceId, populationId);
            //Assert.IsType<List<DeviceProperty>>(response);
        }

        /// <summary>
        /// Test GetDeviceProperty
        /// </summary>
        [Fact]
        public void GetDevicePropertyTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //string populationId = null;
            //string deviceId = null;
            //var response = instance.GetDeviceProperty(id, populationId, deviceId);
            //Assert.IsType<DeviceProperty>(response);
        }

        /// <summary>
        /// Test Post
        /// </summary>
        [Fact]
        public void PostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string populationId = null;
            //string deviceId = null;
            //DeviceProperty deviceProperty = null;
            //instance.Post(populationId, deviceId, deviceProperty);
        }

        /// <summary>
        /// Test Put
        /// </summary>
        [Fact]
        public void PutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //string populationId = null;
            //string deviceId = null;
            //DeviceProperty deviceProperty = null;
            //instance.Put(id, populationId, deviceId, deviceProperty);
        }
    }
}
