/*
 * TaskFlow API
 *
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// NotificationLog
    /// </summary>
    [DataContract(Name = "NotificationLog")]
    public partial class NotificationLog : IEquatable<NotificationLog>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationLog" /> class.
        /// </summary>
        /// <param name="actionDate">actionDate.</param>
        /// <param name="notificationActionId">notificationActionId.</param>
        /// <param name="notificationAction">notificationAction.</param>
        /// <param name="id">id.</param>
        /// <param name="deleted">deleted.</param>
        /// <param name="createdDate">createdDate.</param>
        public NotificationLog(DateTime actionDate = default(DateTime), int notificationActionId = default(int), NotificationAction notificationAction = default(NotificationAction), int id = default(int), bool deleted = default(bool), DateTime createdDate = default(DateTime))
        {
            this.ActionDate = actionDate;
            this.NotificationActionId = notificationActionId;
            this.NotificationAction = notificationAction;
            this.Id = id;
            this.Deleted = deleted;
            this.CreatedDate = createdDate;
        }

        /// <summary>
        /// Gets or Sets ActionDate
        /// </summary>
        [DataMember(Name = "actionDate", EmitDefaultValue = false)]
        public DateTime ActionDate { get; set; }

        /// <summary>
        /// Gets or Sets NotificationActionId
        /// </summary>
        [DataMember(Name = "notificationActionId", EmitDefaultValue = false)]
        public int NotificationActionId { get; set; }

        /// <summary>
        /// Gets or Sets NotificationAction
        /// </summary>
        [DataMember(Name = "notificationAction", EmitDefaultValue = false)]
        public NotificationAction NotificationAction { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Deleted
        /// </summary>
        [DataMember(Name = "deleted", EmitDefaultValue = true)]
        public bool Deleted { get; set; }

        /// <summary>
        /// Gets or Sets CreatedDate
        /// </summary>
        [DataMember(Name = "createdDate", EmitDefaultValue = false)]
        public DateTime CreatedDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NotificationLog {\n");
            sb.Append("  ActionDate: ").Append(ActionDate).Append("\n");
            sb.Append("  NotificationActionId: ").Append(NotificationActionId).Append("\n");
            sb.Append("  NotificationAction: ").Append(NotificationAction).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Deleted: ").Append(Deleted).Append("\n");
            sb.Append("  CreatedDate: ").Append(CreatedDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NotificationLog);
        }

        /// <summary>
        /// Returns true if NotificationLog instances are equal
        /// </summary>
        /// <param name="input">Instance of NotificationLog to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NotificationLog input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ActionDate == input.ActionDate ||
                    (this.ActionDate != null &&
                    this.ActionDate.Equals(input.ActionDate))
                ) && 
                (
                    this.NotificationActionId == input.NotificationActionId ||
                    this.NotificationActionId.Equals(input.NotificationActionId)
                ) && 
                (
                    this.NotificationAction == input.NotificationAction ||
                    (this.NotificationAction != null &&
                    this.NotificationAction.Equals(input.NotificationAction))
                ) && 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.Deleted == input.Deleted ||
                    this.Deleted.Equals(input.Deleted)
                ) && 
                (
                    this.CreatedDate == input.CreatedDate ||
                    (this.CreatedDate != null &&
                    this.CreatedDate.Equals(input.CreatedDate))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActionDate != null)
                {
                    hashCode = (hashCode * 59) + this.ActionDate.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.NotificationActionId.GetHashCode();
                if (this.NotificationAction != null)
                {
                    hashCode = (hashCode * 59) + this.NotificationAction.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                hashCode = (hashCode * 59) + this.Deleted.GetHashCode();
                if (this.CreatedDate != null)
                {
                    hashCode = (hashCode * 59) + this.CreatedDate.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
