/* tslint:disable */
/* eslint-disable */
/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MeasureType,
    MeasureTypeFromJSON,
    MeasureTypeFromJSONTyped,
    MeasureTypeToJSON,
} from './MeasureType';
import {
    Population,
    PopulationFromJSON,
    PopulationFromJSONTyped,
    PopulationToJSON,
} from './Population';
import {
    User,
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface ConfigurationProperty
 */
export interface ConfigurationProperty {
    /**
     * 
     * @type {number}
     * @memberof ConfigurationProperty
     */
    measureTypeId?: number;
    /**
     * 
     * @type {MeasureType}
     * @memberof ConfigurationProperty
     */
    measureType?: MeasureType;
    /**
     * 
     * @type {number}
     * @memberof ConfigurationProperty
     */
    populationId?: number;
    /**
     * 
     * @type {Population}
     * @memberof ConfigurationProperty
     */
    population?: Population;
    /**
     * 
     * @type {string}
     * @memberof ConfigurationProperty
     */
    userId?: string;
    /**
     * 
     * @type {User}
     * @memberof ConfigurationProperty
     */
    user?: User;
    /**
     * 
     * @type {string}
     * @memberof ConfigurationProperty
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfigurationProperty
     */
    value?: string;
    /**
     * 
     * @type {number}
     * @memberof ConfigurationProperty
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ConfigurationProperty
     */
    deleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ConfigurationProperty
     */
    createdDate?: Date;
}

export function ConfigurationPropertyFromJSON(json: any): ConfigurationProperty {
    return ConfigurationPropertyFromJSONTyped(json, false);
}

export function ConfigurationPropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfigurationProperty {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'measureTypeId': !exists(json, 'measureTypeId') ? undefined : json['measureTypeId'],
        'measureType': !exists(json, 'measureType') ? undefined : MeasureTypeFromJSON(json['measureType']),
        'populationId': !exists(json, 'populationId') ? undefined : json['populationId'],
        'population': !exists(json, 'population') ? undefined : PopulationFromJSON(json['population']),
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'user': !exists(json, 'user') ? undefined : UserFromJSON(json['user']),
        'key': !exists(json, 'key') ? undefined : json['key'],
        'value': !exists(json, 'value') ? undefined : json['value'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'deleted': !exists(json, 'deleted') ? undefined : json['deleted'],
        'createdDate': !exists(json, 'createdDate') ? undefined : (new Date(json['createdDate'])),
    };
}

export function ConfigurationPropertyToJSON(value?: ConfigurationProperty | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'measureTypeId': value.measureTypeId,
        'measureType': MeasureTypeToJSON(value.measureType),
        'populationId': value.populationId,
        'population': PopulationToJSON(value.population),
        'userId': value.userId,
        'user': UserToJSON(value.user),
        'key': value.key,
        'value': value.value,
        'id': value.id,
        'deleted': value.deleted,
        'createdDate': value.createdDate === undefined ? undefined : (value.createdDate.toISOString()),
    };
}

