/* tslint:disable */
/* eslint-disable */
/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MeasureType,
    MeasureTypeFromJSON,
    MeasureTypeFromJSONTyped,
    MeasureTypeToJSON,
} from './MeasureType';
import {
    Session,
    SessionFromJSON,
    SessionFromJSONTyped,
    SessionToJSON,
} from './Session';

/**
 * 
 * @export
 * @interface Measure
 */
export interface Measure {
    /**
     * 
     * @type {Date}
     * @memberof Measure
     */
    start?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Measure
     */
    end?: Date;
    /**
     * 
     * @type {number}
     * @memberof Measure
     */
    ordinal?: number;
    /**
     * 
     * @type {string}
     * @memberof Measure
     */
    json?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Measure
     */
    complete?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Measure
     */
    lock?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Measure
     */
    measureTypeId?: number;
    /**
     * 
     * @type {MeasureType}
     * @memberof Measure
     */
    measureType?: MeasureType;
    /**
     * 
     * @type {number}
     * @memberof Measure
     */
    sessionId?: number;
    /**
     * 
     * @type {Session}
     * @memberof Measure
     */
    session?: Session;
    /**
     * 
     * @type {number}
     * @memberof Measure
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Measure
     */
    deleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof Measure
     */
    createdDate?: Date;
}

export function MeasureFromJSON(json: any): Measure {
    return MeasureFromJSONTyped(json, false);
}

export function MeasureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Measure {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': !exists(json, 'start') ? undefined : (new Date(json['start'])),
        'end': !exists(json, 'end') ? undefined : (new Date(json['end'])),
        'ordinal': !exists(json, 'ordinal') ? undefined : json['ordinal'],
        'json': !exists(json, 'json') ? undefined : json['json'],
        'complete': !exists(json, 'complete') ? undefined : json['complete'],
        'lock': !exists(json, 'lock') ? undefined : json['lock'],
        'measureTypeId': !exists(json, 'measureTypeId') ? undefined : json['measureTypeId'],
        'measureType': !exists(json, 'measureType') ? undefined : MeasureTypeFromJSON(json['measureType']),
        'sessionId': !exists(json, 'sessionId') ? undefined : json['sessionId'],
        'session': !exists(json, 'session') ? undefined : SessionFromJSON(json['session']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'deleted': !exists(json, 'deleted') ? undefined : json['deleted'],
        'createdDate': !exists(json, 'createdDate') ? undefined : (new Date(json['createdDate'])),
    };
}

export function MeasureToJSON(value?: Measure | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': value.start === undefined ? undefined : (value.start.toISOString()),
        'end': value.end === undefined ? undefined : (value.end.toISOString()),
        'ordinal': value.ordinal,
        'json': value.json,
        'complete': value.complete,
        'lock': value.lock,
        'measureTypeId': value.measureTypeId,
        'measureType': MeasureTypeToJSON(value.measureType),
        'sessionId': value.sessionId,
        'session': SessionToJSON(value.session),
        'id': value.id,
        'deleted': value.deleted,
        'createdDate': value.createdDate === undefined ? undefined : (value.createdDate.toISOString()),
    };
}

