/* tslint:disable */
/* eslint-disable */
/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NotificationAction,
    NotificationActionFromJSON,
    NotificationActionFromJSONTyped,
    NotificationActionToJSON,
} from './NotificationAction';

/**
 * 
 * @export
 * @interface NotificationLog
 */
export interface NotificationLog {
    /**
     * 
     * @type {Date}
     * @memberof NotificationLog
     */
    actionDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof NotificationLog
     */
    notificationActionId?: number;
    /**
     * 
     * @type {NotificationAction}
     * @memberof NotificationLog
     */
    notificationAction?: NotificationAction;
    /**
     * 
     * @type {number}
     * @memberof NotificationLog
     */
    id?: number;
    /**
     * 
     * @type {boolean}
     * @memberof NotificationLog
     */
    deleted?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof NotificationLog
     */
    createdDate?: Date;
}

export function NotificationLogFromJSON(json: any): NotificationLog {
    return NotificationLogFromJSONTyped(json, false);
}

export function NotificationLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationLog {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actionDate': !exists(json, 'actionDate') ? undefined : (new Date(json['actionDate'])),
        'notificationActionId': !exists(json, 'notificationActionId') ? undefined : json['notificationActionId'],
        'notificationAction': !exists(json, 'notificationAction') ? undefined : NotificationActionFromJSON(json['notificationAction']),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'deleted': !exists(json, 'deleted') ? undefined : json['deleted'],
        'createdDate': !exists(json, 'createdDate') ? undefined : (new Date(json['createdDate'])),
    };
}

export function NotificationLogToJSON(value?: NotificationLog | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actionDate': value.actionDate === undefined ? undefined : (value.actionDate.toISOString()),
        'notificationActionId': value.notificationActionId,
        'notificationAction': NotificationActionToJSON(value.notificationAction),
        'id': value.id,
        'deleted': value.deleted,
        'createdDate': value.createdDate === undefined ? undefined : (value.createdDate.toISOString()),
    };
}

