/* tslint:disable */
/* eslint-disable */
/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivilegeDTO
 */
export interface PrivilegeDTO {
    /**
     * 
     * @type {string}
     * @memberof PrivilegeDTO
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof PrivilegeDTO
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof PrivilegeDTO
     */
    value?: string;
}

export function PrivilegeDTOFromJSON(json: any): PrivilegeDTO {
    return PrivilegeDTOFromJSONTyped(json, false);
}

export function PrivilegeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivilegeDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function PrivilegeDTOToJSON(value?: PrivilegeDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'userId': value.userId,
        'value': value.value,
    };
}

