/* tslint:disable */
/* eslint-disable */
/**
 * TaskFlow API
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionDTO
 */
export interface SessionDTO {
    /**
     * 
     * @type {Date}
     * @memberof SessionDTO
     */
    start?: Date;
    /**
     * 
     * @type {string}
     * @memberof SessionDTO
     */
    administratorId?: string;
    /**
     * 
     * @type {number}
     * @memberof SessionDTO
     */
    sessionStatusId?: number;
    /**
     * 
     * @type {number}
     * @memberof SessionDTO
     */
    sessionTypeId?: number;
    /**
     * 
     * @type {string}
     * @memberof SessionDTO
     */
    subjectId?: string;
}

export function SessionDTOFromJSON(json: any): SessionDTO {
    return SessionDTOFromJSONTyped(json, false);
}

export function SessionDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'start': !exists(json, 'start') ? undefined : (new Date(json['start'])),
        'administratorId': !exists(json, 'administratorId') ? undefined : json['administratorId'],
        'sessionStatusId': !exists(json, 'sessionStatusId') ? undefined : json['sessionStatusId'],
        'sessionTypeId': !exists(json, 'sessionTypeId') ? undefined : json['sessionTypeId'],
        'subjectId': !exists(json, 'subjectId') ? undefined : json['subjectId'],
    };
}

export function SessionDTOToJSON(value?: SessionDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'start': value.start === undefined ? undefined : (value.start.toISOString()),
        'administratorId': value.administratorId,
        'sessionStatusId': value.sessionStatusId,
        'sessionTypeId': value.sessionTypeId,
        'subjectId': value.subjectId,
    };
}

