/*
 * TaskFlow API
 *
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IParticipantsPropertiesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <returns></returns>
        void Delete(int id, string populationId, string participantId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> DeleteWithHttpInfo(int id, string populationId, string participantId);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="participantId"></param>
        /// <param name="populationId"></param>
        /// <returns>List&lt;UserProperty&gt;</returns>
        List<UserProperty> Get(string participantId, string populationId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="participantId"></param>
        /// <param name="populationId"></param>
        /// <returns>ApiResponse of List&lt;UserProperty&gt;</returns>
        ApiResponse<List<UserProperty>> GetWithHttpInfo(string participantId, string populationId);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <returns>UserProperty</returns>
        UserProperty GetUserProperty(int id, string populationId, string participantId);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <returns>ApiResponse of UserProperty</returns>
        ApiResponse<UserProperty> GetUserPropertyWithHttpInfo(int id, string populationId, string participantId);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <returns>UserProperty</returns>
        UserProperty Post(string populationId, string participantId, UserProperty property = default(UserProperty));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <returns>ApiResponse of UserProperty</returns>
        ApiResponse<UserProperty> PostWithHttpInfo(string populationId, string participantId, UserProperty property = default(UserProperty));
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <returns></returns>
        void Put(int id, string populationId, string participantId, UserProperty property = default(UserProperty));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        ApiResponse<Object> PutWithHttpInfo(int id, string populationId, string participantId, UserProperty property = default(UserProperty));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IParticipantsPropertiesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task DeleteAsync(int id, string populationId, string participantId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> DeleteWithHttpInfoAsync(int id, string populationId, string participantId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="participantId"></param>
        /// <param name="populationId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;UserProperty&gt;</returns>
        System.Threading.Tasks.Task<List<UserProperty>> GetAsync(string participantId, string populationId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="participantId"></param>
        /// <param name="populationId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;UserProperty&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<UserProperty>>> GetWithHttpInfoAsync(string participantId, string populationId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserProperty</returns>
        System.Threading.Tasks.Task<UserProperty> GetUserPropertyAsync(int id, string populationId, string participantId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserProperty)</returns>
        System.Threading.Tasks.Task<ApiResponse<UserProperty>> GetUserPropertyWithHttpInfoAsync(int id, string populationId, string participantId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserProperty</returns>
        System.Threading.Tasks.Task<UserProperty> PostAsync(string populationId, string participantId, UserProperty property = default(UserProperty), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserProperty)</returns>
        System.Threading.Tasks.Task<ApiResponse<UserProperty>> PostWithHttpInfoAsync(string populationId, string participantId, UserProperty property = default(UserProperty), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        System.Threading.Tasks.Task PutAsync(int id, string populationId, string participantId, UserProperty property = default(UserProperty), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        System.Threading.Tasks.Task<ApiResponse<Object>> PutWithHttpInfoAsync(int id, string populationId, string participantId, UserProperty property = default(UserProperty), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IParticipantsPropertiesApi : IParticipantsPropertiesApiSync, IParticipantsPropertiesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ParticipantsPropertiesApi : IParticipantsPropertiesApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ParticipantsPropertiesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ParticipantsPropertiesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ParticipantsPropertiesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ParticipantsPropertiesApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ParticipantsPropertiesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ParticipantsPropertiesApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ParticipantsPropertiesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ParticipantsPropertiesApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <returns></returns>
        public void Delete(int id, string populationId, string participantId)
        {
            DeleteWithHttpInfo(id, populationId, participantId);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> DeleteWithHttpInfo(int id, string populationId, string participantId)
        {
            // verify the required parameter 'populationId' is set
            if (populationId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'populationId' when calling ParticipantsPropertiesApi->Delete");
            }

            // verify the required parameter 'participantId' is set
            if (participantId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'participantId' when calling ParticipantsPropertiesApi->Delete");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Org.OpenAPITools.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("populationId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(populationId)); // path parameter
            localVarRequestOptions.PathParameters.Add("participantId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(participantId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Delete<Object>("/v2.0/populations/{populationId}/participants/{participantId}/properties/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Delete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task DeleteAsync(int id, string populationId, string participantId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await DeleteWithHttpInfoAsync(id, populationId, participantId, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> DeleteWithHttpInfoAsync(int id, string populationId, string participantId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'populationId' is set
            if (populationId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'populationId' when calling ParticipantsPropertiesApi->Delete");
            }

            // verify the required parameter 'participantId' is set
            if (participantId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'participantId' when calling ParticipantsPropertiesApi->Delete");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Org.OpenAPITools.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("populationId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(populationId)); // path parameter
            localVarRequestOptions.PathParameters.Add("participantId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(participantId)); // path parameter


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<Object>("/v2.0/populations/{populationId}/participants/{participantId}/properties/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Delete", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="participantId"></param>
        /// <param name="populationId"></param>
        /// <returns>List&lt;UserProperty&gt;</returns>
        public List<UserProperty> Get(string participantId, string populationId)
        {
            Org.OpenAPITools.Client.ApiResponse<List<UserProperty>> localVarResponse = GetWithHttpInfo(participantId, populationId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="participantId"></param>
        /// <param name="populationId"></param>
        /// <returns>ApiResponse of List&lt;UserProperty&gt;</returns>
        public Org.OpenAPITools.Client.ApiResponse<List<UserProperty>> GetWithHttpInfo(string participantId, string populationId)
        {
            // verify the required parameter 'participantId' is set
            if (participantId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'participantId' when calling ParticipantsPropertiesApi->Get");
            }

            // verify the required parameter 'populationId' is set
            if (populationId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'populationId' when calling ParticipantsPropertiesApi->Get");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("participantId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(participantId)); // path parameter
            localVarRequestOptions.PathParameters.Add("populationId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(populationId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<UserProperty>>("/v2.0/populations/{populationId}/participants/{participantId}/properties", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Get", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="participantId"></param>
        /// <param name="populationId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;UserProperty&gt;</returns>
        public async System.Threading.Tasks.Task<List<UserProperty>> GetAsync(string participantId, string populationId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<List<UserProperty>> localVarResponse = await GetWithHttpInfoAsync(participantId, populationId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="participantId"></param>
        /// <param name="populationId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;UserProperty&gt;)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<List<UserProperty>>> GetWithHttpInfoAsync(string participantId, string populationId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'participantId' is set
            if (participantId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'participantId' when calling ParticipantsPropertiesApi->Get");
            }

            // verify the required parameter 'populationId' is set
            if (populationId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'populationId' when calling ParticipantsPropertiesApi->Get");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("participantId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(participantId)); // path parameter
            localVarRequestOptions.PathParameters.Add("populationId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(populationId)); // path parameter


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<UserProperty>>("/v2.0/populations/{populationId}/participants/{participantId}/properties", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Get", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <returns>UserProperty</returns>
        public UserProperty GetUserProperty(int id, string populationId, string participantId)
        {
            Org.OpenAPITools.Client.ApiResponse<UserProperty> localVarResponse = GetUserPropertyWithHttpInfo(id, populationId, participantId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <returns>ApiResponse of UserProperty</returns>
        public Org.OpenAPITools.Client.ApiResponse<UserProperty> GetUserPropertyWithHttpInfo(int id, string populationId, string participantId)
        {
            // verify the required parameter 'populationId' is set
            if (populationId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'populationId' when calling ParticipantsPropertiesApi->GetUserProperty");
            }

            // verify the required parameter 'participantId' is set
            if (participantId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'participantId' when calling ParticipantsPropertiesApi->GetUserProperty");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Org.OpenAPITools.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("populationId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(populationId)); // path parameter
            localVarRequestOptions.PathParameters.Add("participantId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(participantId)); // path parameter


            // make the HTTP request
            var localVarResponse = this.Client.Get<UserProperty>("/v2.0/populations/{populationId}/participants/{participantId}/properties/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserProperty", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserProperty</returns>
        public async System.Threading.Tasks.Task<UserProperty> GetUserPropertyAsync(int id, string populationId, string participantId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<UserProperty> localVarResponse = await GetUserPropertyWithHttpInfoAsync(id, populationId, participantId, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserProperty)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<UserProperty>> GetUserPropertyWithHttpInfoAsync(int id, string populationId, string participantId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'populationId' is set
            if (populationId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'populationId' when calling ParticipantsPropertiesApi->GetUserProperty");
            }

            // verify the required parameter 'participantId' is set
            if (participantId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'participantId' when calling ParticipantsPropertiesApi->GetUserProperty");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Org.OpenAPITools.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("populationId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(populationId)); // path parameter
            localVarRequestOptions.PathParameters.Add("participantId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(participantId)); // path parameter


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<UserProperty>("/v2.0/populations/{populationId}/participants/{participantId}/properties/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserProperty", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <returns>UserProperty</returns>
        public UserProperty Post(string populationId, string participantId, UserProperty property = default(UserProperty))
        {
            Org.OpenAPITools.Client.ApiResponse<UserProperty> localVarResponse = PostWithHttpInfo(populationId, participantId, property);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <returns>ApiResponse of UserProperty</returns>
        public Org.OpenAPITools.Client.ApiResponse<UserProperty> PostWithHttpInfo(string populationId, string participantId, UserProperty property = default(UserProperty))
        {
            // verify the required parameter 'populationId' is set
            if (populationId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'populationId' when calling ParticipantsPropertiesApi->Post");
            }

            // verify the required parameter 'participantId' is set
            if (participantId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'participantId' when calling ParticipantsPropertiesApi->Post");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("populationId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(populationId)); // path parameter
            localVarRequestOptions.PathParameters.Add("participantId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(participantId)); // path parameter
            localVarRequestOptions.Data = property;


            // make the HTTP request
            var localVarResponse = this.Client.Post<UserProperty>("/v2.0/populations/{populationId}/participants/{participantId}/properties", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Post", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UserProperty</returns>
        public async System.Threading.Tasks.Task<UserProperty> PostAsync(string populationId, string participantId, UserProperty property = default(UserProperty), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<UserProperty> localVarResponse = await PostWithHttpInfoAsync(populationId, participantId, property, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UserProperty)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<UserProperty>> PostWithHttpInfoAsync(string populationId, string participantId, UserProperty property = default(UserProperty), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'populationId' is set
            if (populationId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'populationId' when calling ParticipantsPropertiesApi->Post");
            }

            // verify the required parameter 'participantId' is set
            if (participantId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'participantId' when calling ParticipantsPropertiesApi->Post");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "text/plain",
                "application/json",
                "text/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("populationId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(populationId)); // path parameter
            localVarRequestOptions.PathParameters.Add("participantId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(participantId)); // path parameter
            localVarRequestOptions.Data = property;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<UserProperty>("/v2.0/populations/{populationId}/participants/{participantId}/properties", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Post", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <returns></returns>
        public void Put(int id, string populationId, string participantId, UserProperty property = default(UserProperty))
        {
            PutWithHttpInfo(id, populationId, participantId, property);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <returns>ApiResponse of Object(void)</returns>
        public Org.OpenAPITools.Client.ApiResponse<Object> PutWithHttpInfo(int id, string populationId, string participantId, UserProperty property = default(UserProperty))
        {
            // verify the required parameter 'populationId' is set
            if (populationId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'populationId' when calling ParticipantsPropertiesApi->Put");
            }

            // verify the required parameter 'participantId' is set
            if (participantId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'participantId' when calling ParticipantsPropertiesApi->Put");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json",
                "application/json",
                "text/json",
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Org.OpenAPITools.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("populationId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(populationId)); // path parameter
            localVarRequestOptions.PathParameters.Add("participantId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(participantId)); // path parameter
            localVarRequestOptions.Data = property;


            // make the HTTP request
            var localVarResponse = this.Client.Put<Object>("/v2.0/populations/{populationId}/participants/{participantId}/properties/{id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Put", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of void</returns>
        public async System.Threading.Tasks.Task PutAsync(int id, string populationId, string participantId, UserProperty property = default(UserProperty), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            await PutWithHttpInfoAsync(id, populationId, participantId, property, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="populationId"></param>
        /// <param name="participantId"></param>
        /// <param name="property"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Object>> PutWithHttpInfoAsync(int id, string populationId, string participantId, UserProperty property = default(UserProperty), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'populationId' is set
            if (populationId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'populationId' when calling ParticipantsPropertiesApi->Put");
            }

            // verify the required parameter 'participantId' is set
            if (participantId == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'participantId' when calling ParticipantsPropertiesApi->Put");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json-patch+json", 
                "application/json", 
                "text/json", 
                "application/_*+json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("id", Org.OpenAPITools.Client.ClientUtils.ParameterToString(id)); // path parameter
            localVarRequestOptions.PathParameters.Add("populationId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(populationId)); // path parameter
            localVarRequestOptions.PathParameters.Add("participantId", Org.OpenAPITools.Client.ClientUtils.ParameterToString(participantId)); // path parameter
            localVarRequestOptions.Data = property;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<Object>("/v2.0/populations/{populationId}/participants/{participantId}/properties/{id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("Put", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
