/*
 * TaskFlow API
 *
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Connection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConnectionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Connection
        //private Connection instance;

        public ConnectionTests()
        {
            // TODO uncomment below to create an instance of Connection
            //instance = new Connection();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Connection
        /// </summary>
        [Fact]
        public void ConnectionInstanceTest()
        {
            // TODO uncomment below to test "IsType" Connection
            //Assert.IsType<Connection>(instance);
        }


        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'ConnectionID'
        /// </summary>
        [Fact]
        public void ConnectionIDTest()
        {
            // TODO unit test for the property 'ConnectionID'
        }
        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }
        /// <summary>
        /// Test the property 'ConnectionTypeId'
        /// </summary>
        [Fact]
        public void ConnectionTypeIdTest()
        {
            // TODO unit test for the property 'ConnectionTypeId'
        }
        /// <summary>
        /// Test the property 'ConnectionType'
        /// </summary>
        [Fact]
        public void ConnectionTypeTest()
        {
            // TODO unit test for the property 'ConnectionType'
        }
        /// <summary>
        /// Test the property 'PopulationId'
        /// </summary>
        [Fact]
        public void PopulationIdTest()
        {
            // TODO unit test for the property 'PopulationId'
        }
        /// <summary>
        /// Test the property 'Population'
        /// </summary>
        [Fact]
        public void PopulationTest()
        {
            // TODO unit test for the property 'Population'
        }
        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Fact]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'Session'
        /// </summary>
        [Fact]
        public void SessionTest()
        {
            // TODO unit test for the property 'Session'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }

    }

}
