/*
 * TaskFlow API
 *
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Measure
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MeasureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Measure
        //private Measure instance;

        public MeasureTests()
        {
            // TODO uncomment below to create an instance of Measure
            //instance = new Measure();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Measure
        /// </summary>
        [Fact]
        public void MeasureInstanceTest()
        {
            // TODO uncomment below to test "IsType" Measure
            //Assert.IsType<Measure>(instance);
        }


        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Fact]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Fact]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }
        /// <summary>
        /// Test the property 'Ordinal'
        /// </summary>
        [Fact]
        public void OrdinalTest()
        {
            // TODO unit test for the property 'Ordinal'
        }
        /// <summary>
        /// Test the property 'Json'
        /// </summary>
        [Fact]
        public void JsonTest()
        {
            // TODO unit test for the property 'Json'
        }
        /// <summary>
        /// Test the property 'Complete'
        /// </summary>
        [Fact]
        public void CompleteTest()
        {
            // TODO unit test for the property 'Complete'
        }
        /// <summary>
        /// Test the property 'Lock'
        /// </summary>
        [Fact]
        public void LockTest()
        {
            // TODO unit test for the property 'Lock'
        }
        /// <summary>
        /// Test the property 'MeasureTypeId'
        /// </summary>
        [Fact]
        public void MeasureTypeIdTest()
        {
            // TODO unit test for the property 'MeasureTypeId'
        }
        /// <summary>
        /// Test the property 'MeasureType'
        /// </summary>
        [Fact]
        public void MeasureTypeTest()
        {
            // TODO unit test for the property 'MeasureType'
        }
        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Fact]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'Session'
        /// </summary>
        [Fact]
        public void SessionTest()
        {
            // TODO unit test for the property 'Session'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }

    }

}
