/*
 * TaskFlow API
 *
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing MeasureType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MeasureTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MeasureType
        //private MeasureType instance;

        public MeasureTypeTests()
        {
            // TODO uncomment below to create an instance of MeasureType
            //instance = new MeasureType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MeasureType
        /// </summary>
        [Fact]
        public void MeasureTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" MeasureType
            //Assert.IsType<MeasureType>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'StartPath'
        /// </summary>
        [Fact]
        public void StartPathTest()
        {
            // TODO unit test for the property 'StartPath'
        }
        /// <summary>
        /// Test the property 'Properties'
        /// </summary>
        [Fact]
        public void PropertiesTest()
        {
            // TODO unit test for the property 'Properties'
        }
        /// <summary>
        /// Test the property 'PopulationId'
        /// </summary>
        [Fact]
        public void PopulationIdTest()
        {
            // TODO unit test for the property 'PopulationId'
        }
        /// <summary>
        /// Test the property 'Population'
        /// </summary>
        [Fact]
        public void PopulationTest()
        {
            // TODO unit test for the property 'Population'
        }
        /// <summary>
        /// Test the property 'Lock'
        /// </summary>
        [Fact]
        public void LockTest()
        {
            // TODO unit test for the property 'Lock'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }

    }

}
