/*
 * TaskFlow API
 *
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Population
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PopulationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Population
        //private Population instance;

        public PopulationTests()
        {
            // TODO uncomment below to create an instance of Population
            //instance = new Population();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Population
        /// </summary>
        [Fact]
        public void PopulationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Population
            //Assert.IsType<Population>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Measures'
        /// </summary>
        [Fact]
        public void MeasuresTest()
        {
            // TODO unit test for the property 'Measures'
        }
        /// <summary>
        /// Test the property 'MeasureTypes'
        /// </summary>
        [Fact]
        public void MeasureTypesTest()
        {
            // TODO unit test for the property 'MeasureTypes'
        }
        /// <summary>
        /// Test the property 'Sessions'
        /// </summary>
        [Fact]
        public void SessionsTest()
        {
            // TODO unit test for the property 'Sessions'
        }
        /// <summary>
        /// Test the property 'SessionTypes'
        /// </summary>
        [Fact]
        public void SessionTypesTest()
        {
            // TODO unit test for the property 'SessionTypes'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }

    }

}
