/*
 * TaskFlow API
 *
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SessionDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SessionDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SessionDTO
        //private SessionDTO instance;

        public SessionDTOTests()
        {
            // TODO uncomment below to create an instance of SessionDTO
            //instance = new SessionDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SessionDTO
        /// </summary>
        [Fact]
        public void SessionDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" SessionDTO
            //Assert.IsType<SessionDTO>(instance);
        }


        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Fact]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'AdministratorId'
        /// </summary>
        [Fact]
        public void AdministratorIdTest()
        {
            // TODO unit test for the property 'AdministratorId'
        }
        /// <summary>
        /// Test the property 'SessionStatusId'
        /// </summary>
        [Fact]
        public void SessionStatusIdTest()
        {
            // TODO unit test for the property 'SessionStatusId'
        }
        /// <summary>
        /// Test the property 'SessionTypeId'
        /// </summary>
        [Fact]
        public void SessionTypeIdTest()
        {
            // TODO unit test for the property 'SessionTypeId'
        }
        /// <summary>
        /// Test the property 'SubjectId'
        /// </summary>
        [Fact]
        public void SubjectIdTest()
        {
            // TODO unit test for the property 'SubjectId'
        }

    }

}
