/*
 * TaskFlow API
 *
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SessionConfigurationDTO
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SessionConfigurationDTOTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SessionConfigurationDTO
        //private SessionConfigurationDTO instance;

        public SessionConfigurationDTOTests()
        {
            // TODO uncomment below to create an instance of SessionConfigurationDTO
            //instance = new SessionConfigurationDTO();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SessionConfigurationDTO
        /// </summary>
        [Fact]
        public void SessionConfigurationDTOInstanceTest()
        {
            // TODO uncomment below to test "IsType" SessionConfigurationDTO
            //Assert.IsType<SessionConfigurationDTO>(instance);
        }


        /// <summary>
        /// Test the property 'AdministratorId'
        /// </summary>
        [Fact]
        public void AdministratorIdTest()
        {
            // TODO unit test for the property 'AdministratorId'
        }
        /// <summary>
        /// Test the property 'Administrator'
        /// </summary>
        [Fact]
        public void AdministratorTest()
        {
            // TODO unit test for the property 'Administrator'
        }
        /// <summary>
        /// Test the property 'PopulationId'
        /// </summary>
        [Fact]
        public void PopulationIdTest()
        {
            // TODO unit test for the property 'PopulationId'
        }
        /// <summary>
        /// Test the property 'SessionId'
        /// </summary>
        [Fact]
        public void SessionIdTest()
        {
            // TODO unit test for the property 'SessionId'
        }
        /// <summary>
        /// Test the property 'StimulationType'
        /// </summary>
        [Fact]
        public void StimulationTypeTest()
        {
            // TODO unit test for the property 'StimulationType'
        }
        /// <summary>
        /// Test the property 'SubjectId'
        /// </summary>
        [Fact]
        public void SubjectIdTest()
        {
            // TODO unit test for the property 'SubjectId'
        }
        /// <summary>
        /// Test the property 'SessionType'
        /// </summary>
        [Fact]
        public void SessionTypeTest()
        {
            // TODO unit test for the property 'SessionType'
        }
        /// <summary>
        /// Test the property 'Measures'
        /// </summary>
        [Fact]
        public void MeasuresTest()
        {
            // TODO unit test for the property 'Measures'
        }

    }

}
