/*
 * TaskFlow API
 *
 * This API is for interacting with the TaskFlow system. All core operations are handled through this API.
 *
 * The version of the OpenAPI document: v2.0
 * Contact: soude017@umn.edu
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SessionType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SessionTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SessionType
        //private SessionType instance;

        public SessionTypeTests()
        {
            // TODO uncomment below to create an instance of SessionType
            //instance = new SessionType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SessionType
        /// </summary>
        [Fact]
        public void SessionTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" SessionType
            //Assert.IsType<SessionType>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Ordinal'
        /// </summary>
        [Fact]
        public void OrdinalTest()
        {
            // TODO unit test for the property 'Ordinal'
        }
        /// <summary>
        /// Test the property 'PopulationId'
        /// </summary>
        [Fact]
        public void PopulationIdTest()
        {
            // TODO unit test for the property 'PopulationId'
        }
        /// <summary>
        /// Test the property 'Population'
        /// </summary>
        [Fact]
        public void PopulationTest()
        {
            // TODO unit test for the property 'Population'
        }
        /// <summary>
        /// Test the property 'StimulationTypeId'
        /// </summary>
        [Fact]
        public void StimulationTypeIdTest()
        {
            // TODO unit test for the property 'StimulationTypeId'
        }
        /// <summary>
        /// Test the property 'StimulationType'
        /// </summary>
        [Fact]
        public void StimulationTypeTest()
        {
            // TODO unit test for the property 'StimulationType'
        }
        /// <summary>
        /// Test the property 'SessionTypeMeasureTypes'
        /// </summary>
        [Fact]
        public void SessionTypeMeasureTypesTest()
        {
            // TODO unit test for the property 'SessionTypeMeasureTypes'
        }
        /// <summary>
        /// Test the property 'Lock'
        /// </summary>
        [Fact]
        public void LockTest()
        {
            // TODO unit test for the property 'Lock'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Deleted'
        /// </summary>
        [Fact]
        public void DeletedTest()
        {
            // TODO unit test for the property 'Deleted'
        }
        /// <summary>
        /// Test the property 'CreatedDate'
        /// </summary>
        [Fact]
        public void CreatedDateTest()
        {
            // TODO unit test for the property 'CreatedDate'
        }

    }

}
